# Generated by Django 4.2 on 2023-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="sterting_bid",
            new_name="starting_bid",
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="photo",
            field=models.URLField(),
        ),
    ]
