# Generated by Django 4.2 on 2023-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(default='Goods', max_length=30),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
